format code

diff --git a/dot_functions.tmpl b/dot_functions.tmpl
--- a/dot_functions.tmpl
+++ b/dot_functions.tmpl
@@ -1,145 +1,136 @@
-
 #!/usr/bin/env bash
 
 # Create a new directory and enter it
 function mkd() {
-	mkdir -p "$@" && cd "$_";
+	mkdir -p "$@" && cd "$_"
 }
 
 # Change working directory to the top-most Finder window location
 function cdf() { # short for `cdfinder`
-	cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')";
+	cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')"
 }
 
 # Create a .tar.gz archive, using `zopfli`, `pigz` or `gzip` for compression
 function targz() {
-	local tmpFile="${@%/}.tar";
-	tar -cvf "${tmpFile}" --exclude=".DS_Store" "${@}" || return 1;
+	local tmpFile="${@%/}.tar"
+	tar -cvf "${tmpFile}" --exclude=".DS_Store" "${@}" || return 1
 
 	size=$(
-		stat -f"%z" "${tmpFile}" 2> /dev/null; # macOS `stat`
-		stat -c"%s" "${tmpFile}" 2> /dev/null;  # GNU `stat`
-	);
+		stat -f"%z" "${tmpFile}" 2>/dev/null # macOS `stat`
+		stat -c"%s" "${tmpFile}" 2>/dev/null # GNU `stat`
+	)
 
-	local cmd="";
-	if (( size < 52428800 )) && hash zopfli 2> /dev/null; then
+	local cmd=""
+	if ((size < 52428800)) && hash zopfli 2>/dev/null; then
 		# the .tar file is smaller than 50 MB and Zopfli is available; use it
-		cmd="zopfli";
+		cmd="zopfli"
 	else
-		if hash pigz 2> /dev/null; then
-			cmd="pigz";
+		if hash pigz 2>/dev/null; then
+			cmd="pigz"
 		else
-			cmd="gzip";
-		fi;
-	fi;
+			cmd="gzip"
+		fi
+	fi
 
-	echo "Compressing .tar ($((size / 1000)) kB) using \`${cmd}\`…";
-	"${cmd}" -v "${tmpFile}" || return 1;
-	[ -f "${tmpFile}" ] && rm "${tmpFile}";
+	echo "Compressing .tar ($((size / 1000)) kB) using \`${cmd}\`…"
+	"${cmd}" -v "${tmpFile}" || return 1
+	[ -f "${tmpFile}" ] && rm "${tmpFile}"
 
 	zippedSize=$(
-		stat -f"%z" "${tmpFile}.gz" 2> /dev/null; # macOS `stat`
-		stat -c"%s" "${tmpFile}.gz" 2> /dev/null; # GNU `stat`
-	);
+		stat -f"%z" "${tmpFile}.gz" 2>/dev/null # macOS `stat`
+		stat -c"%s" "${tmpFile}.gz" 2>/dev/null # GNU `stat`
+	)
 
-	echo "${tmpFile}.gz ($((zippedSize / 1000)) kB) created successfully.";
+	echo "${tmpFile}.gz ($((zippedSize / 1000)) kB) created successfully."
 }
 
 # Determine size of a file or total size of a directory
 function fs() {
-	if du -b /dev/null > /dev/null 2>&1; then
-		local arg=-sbh;
+	if du -b /dev/null >/dev/null 2>&1; then
+		local arg=-sbh
 	else
-		local arg=-sh;
+		local arg=-sh
 	fi
 	if [[ -n "$@" ]]; then
-		du $arg -- "$@";
+		du $arg -- "$@"
 	else
-		du $arg .[^.]* ./*;
-	fi;
+		du $arg .[^.]* ./*
+	fi
 }
 
 # Use Git’s colored diff when available
-hash git &>/dev/null;
+hash git &>/dev/null
 if [ $? -eq 0 ]; then
 	function diff() {
-		git diff --no-index --color-words "$@";
+		git diff --no-index --color-words "$@"
 	}
-fi;
+fi
 
 # Create a data URL from a file
 function dataurl() {
-	local mimeType=$(file -b --mime-type "$1");
+	local mimeType=$(file -b --mime-type "$1")
 	if [[ $mimeType == text/* ]]; then
-		mimeType="${mimeType};charset=utf-8";
+		mimeType="${mimeType};charset=utf-8"
 	fi
-	echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')";
+	echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')"
 }
 
 # Start an HTTP server from a directory, optionally specifying the port
 function server() {
-	local port="${1:-8000}";
+	local port="${1:-8000}"
 	sleep 1 && open "http://localhost:${port}/" &
 	# Set the default Content-Type to `text/plain` instead of `application/octet-stream`
 	# And serve everything as UTF-8 (although not technically correct, this doesn’t break anything for binary files)
-	python -c $'import SimpleHTTPServer;\nmap = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map;\nmap[""] = "text/plain";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nSimpleHTTPServer.test();' "$port";
+	python -c $'import SimpleHTTPServer;\nmap = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map;\nmap[""] = "text/plain";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nSimpleHTTPServer.test();' "$port"
 }
 
-# Start a PHP server from a directory, optionally specifying the port
-# (Requires PHP 5.4.0+.)
-function phpserver() {
-	local port="${1:-4000}";
-	local ip=$(ipconfig getifaddr en1);
-	sleep 1 && open "http://${ip}:${port}/" &
-	php -S "${ip}:${port}";
-}
 
 # Compare original and gzipped file size
 function gz() {
-	local origsize=$(wc -c < "$1");
-	local gzipsize=$(gzip -c "$1" | wc -c);
-	local ratio=$(echo "$gzipsize * 100 / $origsize" | bc -l);
-	printf "orig: %d bytes\n" "$origsize";
-	printf "gzip: %d bytes (%2.2f%%)\n" "$gzipsize" "$ratio";
+	local origsize=$(wc -c <"$1")
+	local gzipsize=$(gzip -c "$1" | wc -c)
+	local ratio=$(echo "$gzipsize * 100 / $origsize" | bc -l)
+	printf "orig: %d bytes\n" "$origsize"
+	printf "gzip: %d bytes (%2.2f%%)\n" "$gzipsize" "$ratio"
 }
 
 # Run `dig` and display the most useful info
 function digga() {
-	dig +nocmd "$1" any +multiline +noall +answer;
+	dig +nocmd "$1" any +multiline +noall +answer
 }
 
 # Show all the names (CNs and SANs) listed in the SSL certificate
 # for a given domain
 function getcertnames() {
 	if [ -z "${1}" ]; then
-		echo "ERROR: No domain specified.";
-		return 1;
-	fi;
+		echo "ERROR: No domain specified."
+		return 1
+	fi
 
-	local domain="${1}";
-	echo "Testing ${domain}…";
-	echo ""; # newline
+	local domain="${1}"
+	echo "Testing ${domain}…"
+	echo "" # newline
 
-	local tmp=$(echo -e "GET / HTTP/1.0\nEOT" \
-		| openssl s_client -connect "${domain}:443" -servername "${domain}" 2>&1);
+	local tmp=$(echo -e "GET / HTTP/1.0\nEOT" |
+		openssl s_client -connect "${domain}:443" -servername "${domain}" 2>&1)
 
 	if [[ "${tmp}" = *"-----BEGIN CERTIFICATE-----"* ]]; then
-		local certText=$(echo "${tmp}" \
-			| openssl x509 -text -certopt "no_aux, no_header, no_issuer, no_pubkey, \
-			no_serial, no_sigdump, no_signame, no_validity, no_version");
-		echo "Common Name:";
-		echo ""; # newline
-		echo "${certText}" | grep "Subject:" | sed -e "s/^.*CN=//" | sed -e "s/\/emailAddress=.*//";
-		echo ""; # newline
-		echo "Subject Alternative Name(s):";
-		echo ""; # newline
-		echo "${certText}" | grep -A 1 "Subject Alternative Name:" \
-			| sed -e "2s/DNS://g" -e "s/ //g" | tr "," "\n" | tail -n +2;
-		return 0;
+		local certText=$(echo "${tmp}" |
+			openssl x509 -text -certopt "no_aux, no_header, no_issuer, no_pubkey, \
+			no_serial, no_sigdump, no_signame, no_validity, no_version")
+		echo "Common Name:"
+		echo "" # newline
+		echo "${certText}" | grep "Subject:" | sed -e "s/^.*CN=//" | sed -e "s/\/emailAddress=.*//"
+		echo "" # newline
+		echo "Subject Alternative Name(s):"
+		echo "" # newline
+		echo "${certText}" | grep -A 1 "Subject Alternative Name:" |
+			sed -e "2s/DNS://g" -e "s/ //g" | tr "," "\n" | tail -n +2
+		return 0
 	else
-		echo "ERROR: Certificate not found.";
-		return 1;
-	fi;
+		echo "ERROR: Certificate not found."
+		return 1
+	fi
 }
 
 # Normalize `open` across Linux, macOS, and Windows.
@@ -147,9 +138,9 @@ function getcertnames() {
 if [ ! $(uname -s) = 'Darwin' ]; then
 	if grep -q Microsoft /proc/version; then
 		# Ubuntu on Windows using the Linux subsystem
-		alias open='explorer.exe';
+		alias open='explorer.exe'
 	else
-		alias open='xdg-open';
+		alias open='xdg-open'
 	fi
 fi
 
@@ -157,10 +148,10 @@ fi
 # location
 function o() {
 	if [ $# -eq 0 ]; then
-		open .;
+		open .
 	else
-		open "$@";
-	fi;
+		open "$@"
+	fi
 }
 
 # `tre` is a shorthand for `tree` with hidden files and color enabled, ignoring
@@ -168,58 +159,73 @@ function o() {
 # `less` with options to preserve color and line numbers, unless the output is
 # small enough for one screen.
 function tre() {
-	tree -aC -I '.git|node_modules|bower_components' --dirsfirst "$@" | less -FRNX;
+	tree -aC -I '.git|node_modules|bower_components' --dirsfirst "$@" | less -FRNX
 }
 
 # 设置全局代理
+# 参数：
+#   $1 - 代理端口，默认为 7890
+# 示例：
+#   proxyon 7890
 function proxyon() {
-	export HTTPS_PROXY=http://127.0.0.1:7890
-	export HTTP_PROXY=http://127.0.0.1:7890
-  export ALL_PROXY=socks5://127.0.0.1:7890
+	local port=${1:-7890}
+	export HTTPS_PROXY=http://127.0.0.1:$port
+	export HTTP_PROXY=http://127.0.0.1:$port
+	export ALL_PROXY=socks5://127.0.0.1:$port
 }
-
 
 # 取消全局代理设置
-
 function proxyoff() {
- unset HTTPS_PROXY
- unset HTTP_PROXY
- unset ALL_PROXY
+	unset HTTPS_PROXY
+	unset HTTP_PROXY
+	unset ALL_PROXY
 }
-
 
 function appendPath() {
 	local dest="export PATH=\"${1}:\$PATH\""
 	# echo ${  grep -q "${dest}" ~/.path}
 	[ -f ~/.path ] && echo " exists."
-    if ! grep -q ${dest} ~/.path ; then
+	if ! grep -q ${dest} ~/.path; then
 		echo success append $dest to path
-		echo ${dest} >> ~/.path
+		echo ${dest} >>~/.path
 		source ~/.path
-    fi
+	fi
 
 }
 
+# create_split_bw_item 创建并分割 Bitwarden 项目。 当文件内容超过 5000 个字符时，会自动分割为多个项目。
+# 最终生成的项目名称为：${name}_1, ${name}_2, ${name}_3, ...
+# 参数：
+#   $1 - Bitwarden 项目的名称
+#   $2 - Bitwarden 项目的内容的文件路径
+# 示例：
+#   create_split_bw_item "id_rsa" ～/.ssh/id_rsa
 function create_split_bw_item() {
-    local name=$1
-    local file_path=$2
-    local content=$(cat $file_path)
-    local length=${#content}
-    local max_length=5000
-    local part=1
+	local name=$1
+	local file_path=$2
+	local content=$(cat $file_path)
+	local length=${#content}
+	local max_length=5000
+	local part=1
 
-    while [ $length -gt 0 ]; do
-        local notes=${content:0:$max_length}
-        echo "$notes"
-        echo "{\"organizationId\":null,\"folderId\":null,\"type\":2,\"name\":\"${name}_$part\",\"notes\":\"$(echo $notes | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\\\n/g')\",\"favorite\":false,\"fields\":[],\"login\":null,\"secureNote\":{\"type\":0},\"card\":null,\"identity\":null}" | bw encode | bw create item
-        content=${content:$max_length}
-        length=${#content}
-        ((part++))
-    done
+	while [ $length -gt 0 ]; do
+		local notes=${content:0:$max_length}
+		echo "$notes"
+		echo "{\"organizationId\":null,\"folderId\":null,\"type\":2,\"name\":\"${name}_$part\",\"notes\":\"$(echo $notes | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\\\n/g')\",\"favorite\":false,\"fields\":[],\"login\":null,\"secureNote\":{\"type\":0},\"card\":null,\"identity\":null}" | bw encode | bw create item
+		content=${content:$max_length}
+		length=${#content}
+		((part++))
+	done
 }
 
+# create_bw_item 创建 Bitwarden 项目。
+# 参数：
+#   $1 - Bitwarden 项目的名称
+#   $2 - Bitwarden 项目的内容的文件路径
+# 示例：
+#   create_bw_item "id_rsa" ～/.ssh/id_rsa
 function create_bw_item() {
-  local name=$1
-  local file_path=$2
-  echo "{\"organizationId\":null,\"folderId\":null,\"type\":2,\"name\":\"$name\",\"notes\":\"$(sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\\\n/g' $file_path)\",\"favorite\":false,\"fields\":[],\"login\":null,\"secureNote\":{\"type\":0},\"card\":null,\"identity\":null}" | bw encode | bw create item
+	local name=$1
+	local file_path=$2
+	echo "{\"organizationId\":null,\"folderId\":null,\"type\":2,\"name\":\"$name\",\"notes\":\"$(sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\\\n/g' $file_path)\",\"favorite\":false,\"fields\":[],\"login\":null,\"secureNote\":{\"type\":0},\"card\":null,\"identity\":null}" | bw encode | bw create item
 }
